### ISSUE TITLE
Channel issues

### ISSUE THREAD

**Issue by ghost** [coder-alpha/CcloudTv.bundle#5]
Hey i checked on ccloud a channel is working on the website but its not showing up on the channel?

**Comment by ghost** [comment]
This is also not just one channel its with alot of channels at least 100+

**Comment by coder-alpha** [comment]
Yes, i'm aware of it and that's mostly due to device support by Plex. The channels that are not working are rtmp channels which none of the Plex devices support. However, they work when using Chrome browser Plex Web interface. They are listed under 'Test' category named RtmpTestChannels...

Are you having issues with any m3u8 channels that work on their website but not on Plex App ? 

I'll be pushing out an alpha version of the new cCloud Plex App with an experimental transcoder to handle rtmp channels within 1-2 days with information on the Plex thread https://forums.plex.tv/discussion/166602/rel-ccloudtv-channel-iptv#latest

**Comment by ghost** [comment]
Oh ok can i download the expiermental plex app it would be really usefull for me

**Comment by coder-alpha** [comment]
I'm still fixing a few issues/bugs the new changes have caused but hope to have it on git later tonite (hopefully) or positively by tomorrow. It wont be useful with these bugs/issues as of now.

**Comment by ghost** [comment]
So it will be on your main github page corrrect?

**Comment by coder-alpha** [comment]
Finally out now.. had more work required and testing than I initially thought https://github.com/coder-alpha/CcloudTv.bundle/releases
